import { Platform } from 'react-native';
import * as LucideNative from 'lucide-react-native';
import * as LucideWeb from 'lucide-react';

const isWeb = Platform.OS === 'web';
const Icons = isWeb ? LucideWeb : LucideNative;

export const ShoppingCart = (Icons as any).ShoppingCart || (Icons as any).ShoppingBag;
export const Utensils = (Icons as any).Utensils || (Icons as any).Coffee;
export const Home = (Icons as any).Home;
export const Zap = (Icons as any).Zap;
export const Car = (Icons as any).Car;
export const Film = (Icons as any).Film;
export const Activity = (Icons as any).Activity;
export const Tv = (Icons as any).Tv;
export const Briefcase = (Icons as any).Briefcase;
export const TrendingUp = (Icons as any).TrendingUp;
export const TrendingDown = (Icons as any).TrendingDown;
export const PieChart = (Icons as any).PieChart;
export const PlusCircle = (Icons as any).PlusCircle;
export const Book = (Icons as any).Book;
export const ShoppingBag = (Icons as any).ShoppingBag;
export const HelpCircle = (Icons as any).HelpCircle;
export const ChevronLeft = (Icons as any).ChevronLeft;
export const ChevronRight = (Icons as any).ChevronRight;
export const Wallet = (Icons as any).Wallet;
export const AlertTriangle = (Icons as any).AlertTriangle;
export const Plus = (Icons as any).Plus;
export const CreditCard = (Icons as any).CreditCard;
export const Banknote = (Icons as any).Banknote;
export const ArrowUpRight = (Icons as any).ArrowUpRight;
export const Trash2 = (Icons as any).Trash2;
export const ArrowRightLeft = (Icons as any).ArrowRightLeft;
export const Search = (Icons as any).Search;
export const Filter = (Icons as any).Filter;
export const Calendar = (Icons as any).Calendar;
export const Server = (Icons as any).Server;
export const DollarSign = (Icons as any).DollarSign;
export const Target = (Icons as any).Target;
export const Database = (Icons as any).Database;
export const Check = (Icons as any).Check;
export const RefreshCw = (Icons as any).RefreshCw;
export const LayoutDashboard = (Icons as any).LayoutDashboard;
export const History = (Icons as any).History;
export const Settings = (Icons as any).Settings;
export const Sparkles = (Icons as any).Sparkles || (Icons as any).Zap;
export const X = (Icons as any).X || (Icons as any).Plus;
export const Edit3 = (Icons as any).Edit3 || (Icons as any).Plus;
